/* Replace # with the real Auntie Anne's gift-card URL before sharing. */
const GIFT_LINK = '#';
const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const W = 960, H = 540;

const ui = Object.fromEntries(['titleScreen','storyScreen','levelScreen','endingScreen','hud','controls','dialogue','toast','bossHud','actLabel','levelLabel','hearts','cream','rescued','goalPill','bossName','bossBar','storyArt','storyKicker','storyTitle','storyText','storyQuote','pageNumber','levelKicker','levelTitle','levelDescription','levelMission'].map(id=>[id,document.querySelector('#'+id)]));
document.querySelector('#giftLink').href = GIFT_LINK;

const STORY = [
  {art:'town',kicker:'Twistwick • one peaceful morning',title:'A perfectly twisted town',text:'The Pretzel People were preparing for Catherine’s birthday. Banners were hung, cakes were baked, and nobody could agree which way was up.',quote:'Mayor Twistopher: “This festival will go exactly as planned.”'},
  {art:'invasion',kicker:'Unfortunately • five minutes later',title:'Enter King Glazebald',text:'A frosting-powered chariot darkened the sky. King Glazebald the Holehearted and his Donut Legion demanded the town surrender.',quote:'Glazebald: “Your celebration has insufficient frosting!”'},
  {art:'cages',kicker:'The great sprinkle raid',title:'The pretzels are taken',text:'The Legion trapped five townspeople in candy cages and stole the Golden Salt Crystals that protected Twistwick.',quote:'Mayor: “We have mustard?”  Glazebald: “Revolting. Arrest everyone.”'},
  {art:'door',kicker:'Meanwhile • Cat’s breakfast',title:'A knock at the door',text:'The escapees found Catherine “Cat” Crumbwell: bagel girl, reluctant hero, and owner of one rapidly cooling coffee.',quote:'Cat: “Have you considered calling someone who isn’t eating breakfast?”'},
  {art:'hero',kicker:'A heroic sigh later',title:'The Cream Cheese Sling',text:'Auntie Saltina handed Cat the ancient sling. She fastened her cape, adjusted her Roman helmet, and accepted the quest.',quote:'Cat: “Fine. But this counts as cardio.”'}
];

const LEVELS = [
  {act:'ACT I',name:'Crumbly Commons',desc:'A gentle first route through toast hills, tiny jam gaps, and a few overconfident pastries.',mission:'Rescue Mayor Twistopher • Reach the bakery gate',width:2200,start:{x:90,y:360},exit:2080,theme:'meadow',
    platforms:[[0,460,720,90],[780,460,720,90],[1560,460,640,90],[360,370,180,22],[900,365,190,22],[1320,350,190,22],[1740,370,190,22]],
    hazards:[[720,455,60,85],[1500,455,60,85]], cages:[[1250,385,'Mayor Twistopher']], checkpoints:[1100], enemies:[[650,400,'scout'],[1050,305,'archer'],[1720,400,'roller']], switches:[], boss:null},
  {act:'ACT II',name:'Sprinkleworks',desc:'The factory is still dramatic, but its safety department has installed wider walkways.',mission:'Rescue two pretzels • Defeat Sir Sprinkles',width:2500,start:{x:80,y:360},exit:2390,theme:'factory',
    platforms:[[0,460,780,90],[850,460,690,90],[1610,460,890,90],[300,370,190,22],[930,355,190,22],[1320,365,190,22],[1750,350,190,22],[2040,375,200,22]],
    hazards:[[780,455,70,85],[1540,455,70,85]], cages:[[1000,385,'Knottingham'],[1650,385,'Auntie Saltina']],checkpoints:[1260],enemies:[[700,400,'scout'],[1280,305,'archer'],[1840,400,'roller']],switches:[],boss:{x:2160,y:378,kind:'sprinkles',hp:4}},
  {act:'ACT III',name:'The Glazed Gauntlet',desc:'A forgiving climb to the throne room, followed by one very theatrical donut.',mission:'Rescue the final two pretzels • Defeat King Glazebald',width:2850,start:{x:70,y:360},exit:2740,theme:'castle',
    platforms:[[0,460,820,90],[890,460,730,90],[1690,460,1160,90],[340,370,190,22],[990,350,190,22],[1350,365,190,22],[1810,345,200,22],[2120,375,200,22]],
    hazards:[[820,455,70,85],[1620,455,70,85]],cages:[[1100,385,'Baker Braidley'],[1780,385,'Little Loop']],checkpoints:[1380,1980],enemies:[[720,400,'scout'],[1400,305,'archer'],[1940,400,'roller']],switches:[],boss:{x:2380,y:350,kind:'king',hp:6}}
];

let scene='title', storyIndex=0, levelIndex=0, level=null, last=0, camera=0, totalRescued=0, muted=false, audio=null, toastTimer=0, dialogueQueue=[], dialogueDone=null;
let platforms=[], hazards=[], cages=[], enemies=[], projectiles=[], particles=[], switches=[], checkpoint={x:90,y:360};
const input={left:false,right:false,jump:false,shoot:false,jumpPress:false,shootPress:false};
const hero={x:90,y:350,w:44,h:62,vx:0,vy:0,dir:1,onGround:false,coyote:0,jumpBuffer:0,hearts:3,cream:8,creamClock:0,shootCd:0,invuln:0};

function hideOverlays(){['titleScreen','storyScreen','levelScreen','endingScreen'].forEach(k=>ui[k].classList.add('hidden'));}
function show(el){el?.classList.remove('hidden')} function hide(el){el?.classList.add('hidden')}
function tone(freq=440,d=.08,type='sine'){if(muted)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function say(text,time=1800){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),time)}
function updateHud(){ui.hearts.textContent='♥ '.repeat(hero.hearts).trim()+' ♡ '.repeat(3-hero.hearts).trim();ui.cream.textContent=Math.floor(hero.cream);ui.rescued.textContent=totalRescued+'/5';if(!level)return;const boss=enemies.find(e=>!e.dead&&(e.kind==='sprinkles'||e.kind==='king'));ui.goalPill.textContent=!cages.every(c=>c.saved)?'FIND THE PRETZELS →':boss?'DEFEAT THE BOSS →':'REACH THE GATE →'}
function storyStart(){scene='story';storyIndex=0;hideOverlays();show(ui.storyScreen);renderStory()}
function renderStory(){const s=STORY[storyIndex];ui.storyArt.className='story-art '+s.art;ui.storyKicker.textContent=s.kicker;ui.storyTitle.textContent=s.title;ui.storyText.textContent=s.text;ui.storyQuote.textContent=s.quote;ui.pageNumber.textContent=(storyIndex+1)+' / '+STORY.length;document.querySelector('#nextStory').innerHTML=storyIndex===STORY.length-1?'Begin the quest <b>→</b>':'Next <b>→</b>';drawBackdrop()}
function nextStory(){tone(620,.08);if(++storyIndex>=STORY.length)return showLevelIntro(0);renderStory()}
function showLevelIntro(i){levelIndex=i;scene='levelIntro';hideOverlays();hide(ui.hud);hide(ui.controls);const l=LEVELS[i];ui.levelKicker.textContent=l.act;ui.levelTitle.textContent=l.name;ui.levelDescription.textContent=l.desc;ui.levelMission.textContent=l.mission;ui.actLabel.textContent=l.act;ui.levelLabel.textContent=l.name;show(ui.levelScreen);drawBackdrop()}
function loadLevel(i){levelIndex=i;level=LEVELS[i];scene='play';hideOverlays();show(ui.hud);show(ui.controls);hide(ui.bossHud);platforms=level.platforms.map(a=>({x:a[0],y:a[1],w:a[2],h:a[3],active:true}));hazards=level.hazards.map(a=>({x:a[0],y:a[1],w:a[2],h:a[3]}));cages=level.cages.map((a,n)=>({x:a[0],y:a[1],w:58,h:72,name:a[2],hp:1,saved:false,id:n}));switches=[];enemies=level.enemies.map((a,n)=>makeEnemy(a[0],a[1],a[2],n));if(level.boss)enemies.push(makeBoss(level.boss));projectiles=[];particles=[];checkpoint={...level.start};Object.assign(hero,{x:level.start.x,y:level.start.y,vx:0,vy:0,hearts:3,cream:8,invuln:0});camera=0;updateHud();queueDialogue(levelDialogue(i));}
function levelDialogue(i){return i===0?[["Mayor Twistopher","🥨","Cat! One schmear hit opens a cage. We simplified the locks after several complaints."],["Cat Crumbwell","◎","Move, jump, shoot. Finally, instructions I can respect."]]:i===1?[["Cat Crumbwell","◎","A factory powered by sprinkles. Somehow this is still not the strangest Tuesday I've had."],["Sir Sprinkles","🍩","Trespasser! Prepare for a moderately challenging duel!"]]:[["Little Loop","🥨","Glazebald talks a lot, but ordinary cream cheese works perfectly."],["Cat Crumbwell","◎","Excellent. I brought eight scoops and very little patience."]]}
function makeEnemy(x,y,kind,n){return{x,y,w:kind==='roller'?54:50,h:kind==='roller'?54:58,kind,hp:kind==='roller'?2:1,maxHp:kind==='roller'?2:1,baseX:x,dir:n%2?1:-1,speed:kind==='roller'?62:34,cool:1.4+n*.2,dead:false,flash:0}}
function makeBoss(b){return{x:b.x,y:b.y,w:b.kind==='king'?105:76,h:b.kind==='king'?105:82,kind:b.kind,hp:b.hp,maxHp:b.hp,baseX:b.x,dir:-1,speed:b.kind==='king'?85:60,cool:1.4,dead:false,flash:0,phase:1,state:'idle',stateClock:0}}
function queueDialogue(lines,done=null){dialogueQueue=[...lines];dialogueDone=done;scene='dialogue';show(ui.dialogue);advanceDialogue()}
function advanceDialogue(){if(!dialogueQueue.length){hide(ui.dialogue);scene='play';const done=dialogueDone;dialogueDone=null;if(done)done();return}const [name,portrait,text]=dialogueQueue.shift();document.querySelector('#speaker').textContent=name;document.querySelector('#portrait').textContent=portrait;document.querySelector('#dialogueText').textContent=text;tone(360,.04,'triangle')}

function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function solidCollision(prevY){hero.onGround=false;for(const p of platforms){if(!p.active)continue;if(hero.x+hero.w>p.x&&hero.x<p.x+p.w&&hero.y+hero.h>=p.y&&prevY+hero.h<=p.y+8&&hero.vy>=0){hero.y=p.y-hero.h;hero.vy=0;hero.onGround=true}}}
function updateHero(dt){hero.shootCd=Math.max(0,hero.shootCd-dt);hero.invuln=Math.max(0,hero.invuln-dt);hero.creamClock+=dt;if(hero.cream<8&&hero.creamClock>1.35){hero.cream=Math.min(8,hero.cream+1);hero.creamClock=0;updateHud()}
  if(input.jumpPress)hero.jumpBuffer=.13;else hero.jumpBuffer=Math.max(0,hero.jumpBuffer-dt);hero.coyote=hero.onGround?.11:Math.max(0,hero.coyote-dt);
  const move=(input.right?1:0)-(input.left?1:0);if(move)hero.dir=move;
  hero.vx+=move*1500*dt;hero.vx*=Math.pow(move?.07:.0004,dt);hero.vx=Math.max(-285,Math.min(285,hero.vx));hero.vy+=1200*dt;hero.vy=Math.min(hero.vy,700);
  if(hero.jumpBuffer>0&&hero.coyote>0){hero.vy=-500;hero.jumpBuffer=0;hero.coyote=0;burst(hero.x+22,hero.y+62,'#fff0c9',7);tone(460,.08,'square')}
  if(!input.jump&&hero.vy< -190)hero.vy=-190;const prevY=hero.y;hero.x+=hero.vx*dt;hero.y+=hero.vy*dt;hero.x=Math.max(0,Math.min(level.width-hero.w,hero.x));solidCollision(prevY);
  if(input.shootPress)shoot();for(const h of hazards)if(overlap(hero,h))hurtHero();if(hero.y>H+170)respawn();for(const e of enemies)if(!e.dead&&overlap(hero,e))hurtHero(e.x);for(const c of cages)if(c.saved&&Math.abs(hero.x-c.x)<55)c.collected=true;
  for(const cp of level.checkpoints)if(hero.x>cp&&checkpoint.x<cp){checkpoint={x:cp,y:340};say('Checkpoint: fresh coffee acquired ☕');tone(720,.1)}
  if(hero.x>level.exit&&cages.every(c=>c.saved)&&!enemies.some(e=>!e.dead&&(e.kind==='sprinkles'||e.kind==='king')))finishLevel();else if(hero.x>level.exit-80&&!cages.every(c=>c.saved))say('The gate needs every Salt Crystal!')
}
function shoot(){if(hero.shootCd>0||hero.cream<1)return say('Out of schmear — give it a second!');hero.shootCd=.28;hero.cream--;hero.creamClock=0;projectiles.push({x:hero.x+22+hero.dir*25,y:hero.y+25,w:18,h:14,vx:hero.dir*570,vy:-15,owner:'hero',life:1.6,kind:'cream'});updateHud();tone(290,.06,'triangle')}
function hurtHero(from=hero.x){if(hero.invuln>0)return;hero.hearts--;hero.invuln=1.35;hero.vx=hero.x<from?-260:260;hero.vy=-260;shake();tone(110,.16,'sawtooth');updateHud();if(hero.hearts<=0)setTimeout(respawn,350)}
function respawn(){hero.hearts=3;hero.x=checkpoint.x;hero.y=checkpoint.y;hero.vx=hero.vy=0;hero.invuln=1.2;updateHud();say('Cat returns with renewed determination.')}
function shake(){const card=document.querySelector('.game-card');card.classList.remove('shake');void card.offsetWidth;card.classList.add('shake')}
function burst(x,y,color,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*230,vy:-60-Math.random()*180,life:.5+Math.random()*.4,color,r:3+Math.random()*4})}

function updateEnemies(dt){for(const e of enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);e.cool-=dt;e.stateClock=(e.stateClock||0)-dt;
    if(e.kind==='king'){updateKing(e,dt);continue}if(e.kind==='sprinkles'){e.x+=e.dir*e.speed*dt;if(Math.abs(e.x-e.baseX)>180)e.dir*=-1;if(e.cool<=0){enemyShot(e,'sprinkle');e.cool=1.25}continue}
    e.x+=e.dir*e.speed*dt;if(Math.abs(e.x-e.baseX)>(e.kind==='archer'?35:85))e.dir*=-1;if(e.kind==='archer'&&e.cool<=0&&Math.abs(hero.x-e.x)<560){enemyShot(e,'sugar');e.cool=1.7}
  }enemies=enemies.filter(e=>!e.dead)}
function updateKing(e,dt){if(e.phase===1){e.x=e.baseX+Math.sin(performance.now()/800)*75;if(e.cool<=0){enemyShot(e,'orb');e.cool=1.55}}else{e.state='roll';e.x+=e.dir*145*dt;if(e.x<e.baseX-230||e.x>e.baseX+230)e.dir*=-1}}
function enemyShot(e,kind){const dx=hero.x-e.x,dy=hero.y-e.y,d=Math.hypot(dx,dy)||1;projectiles.push({x:e.x+e.w/2,y:e.y+25,w:kind==='orb'?24:15,h:kind==='orb'?24:15,vx:dx/d*(kind==='orb'?220:190),vy:dy/d*(kind==='orb'?220:190),owner:'enemy',life:4,kind});tone(kind==='orb'?140:210,.07,'square')}
function updateProjectiles(dt){for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.kind==='cream')p.vy+=80*dt;
    if(p.owner==='enemy'&&overlap(p,hero)){p.life=0;hurtHero(p.x)}
    for(const c of cages)if(!c.saved&&overlap(p,c)&&p.owner==='hero'){p.life=0;c.hp--;burst(p.x,p.y,'#f3c84f',8);if(c.hp<=0)rescue(c)}
    for(const e of enemies)if(!e.dead&&overlap(p,e)&&p.owner==='hero'){p.life=0;hitEnemy(e,p)}
  }projectiles=projectiles.filter(p=>p.life>0&&p.x>-100&&p.x<level.width+100&&p.y<700)}
function hitEnemy(e,p){if(e.kind==='king'){e.hp--;e.flash=.18;burst(p.x,p.y,'#f0a2c0',14);shake();tone(170,.08,'square');if(e.phase===1&&e.hp===3){e.phase=2;e.state='roll';queueDialogue([["King Glazebald","🍩","Impossible! Initiate rolling majestically!"],["Cat Crumbwell","◎","That is just rolling. Keep shooting, Catherine."]]);return}if(e.hp<=0)defeatBoss(e);updateHud();return}
  e.hp--;e.flash=.15;burst(p.x,p.y,'#fff0c8',8);if(e.hp<=0){e.dead=true;updateHud();tone(160,.12,'sawtooth');if(e.kind==='sprinkles')queueDialogue([["Sir Sprinkles","🍩","I have been... lightly spread."],["Cat Crumbwell","◎","You fought bravely. Incorrectly, but bravely."]]);}}
function defeatBoss(e){e.dead=true;hide(ui.bossHud);updateHud();for(let i=0;i<70;i++)burst(e.x+e.w/2,e.y+e.h/2,['#f4bb4f','#e75f7b','#8b72bd'][i%3],1);queueDialogue([["King Glazebald","🍩","You’ve struck my one obvious weakness!"],["Cat Crumbwell","◎","The enormous hole?"],["King Glazebald","🍩","…Yes."]]);tone(90,.4,'sawtooth')}
function rescue(c){c.saved=true;totalRescued++;burst(c.x+29,c.y+35,'#f6cf55',22);tone(820,.15,'triangle');setTimeout(()=>tone(1040,.18,'triangle'),100);say(c.name+' rescued! Keep moving →');updateHud()}
function finishLevel(){if(scene!=='play')return;if(levelIndex<LEVELS.length-1){scene='transition';document.querySelector('.game-card').classList.add('flash');setTimeout(()=>{document.querySelector('.game-card').classList.remove('flash');showLevelIntro(levelIndex+1)},400)}else{scene='endingStory';hide(ui.hud);hide(ui.controls);queueDialogue([["Mayor Twistopher","🥨","Cat Crumbwell, you rescued our people and saved Twistwick!"],["Cat Crumbwell","◎","And ruined a perfectly good helmet."],["Auntie Saltina","🥨","Please accept the highest honor our people can bestow."]],showEnding)}}
function showEnding(){scene='ending';hide(ui.dialogue);hide(ui.hud);hide(ui.controls);hide(ui.bossHud);show(ui.endingScreen);confetti(160);tone(523,.15);setTimeout(()=>tone(659,.15),160);setTimeout(()=>tone(784,.3),320)}
function confetti(n){for(let i=0;i<n;i++)particles.push({x:Math.random()*W,y:-Math.random()*H,vx:(Math.random()-.5)*150,vy:70+Math.random()*160,life:6,color:['#ef6380','#f3bc4d','#75b89a','#9575bd'][i%4],r:3+Math.random()*5,screen:true})}

function update(dt){if(scene==='play'){updateHero(dt);updateEnemies(dt);updateProjectiles(dt);const boss=enemies.find(e=>e.kind==='king'||e.kind==='sprinkles');if(boss&&Math.abs(hero.x-boss.x)<620){show(ui.bossHud);ui.bossName.textContent=boss.kind==='king'?'KING GLAZEBALD':'SIR SPRINKLES';ui.bossBar.style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%'}else hide(ui.bossHud);camera+=(Math.max(0,Math.min(level.width-W,hero.x-W*.38))-camera)*Math.min(1,dt*5)}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=(p.screen?80:380)*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);input.jumpPress=input.shootPress=false}

function circle(x,y,r,fill,stroke='#4b334e',lw=3){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.lineWidth=lw;ctx.strokeStyle=stroke;ctx.stroke()}}
function drawBackdrop(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#83cdd8');g.addColorStop(1,'#f8d990');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawCloud(100,95,1);drawCloud(520,145,.75);drawCloud(820,80,.9);ctx.fillStyle='#a286bd';ctx.beginPath();ctx.arc(120,520,260,Math.PI,0);ctx.arc(510,520,310,Math.PI,0);ctx.arc(910,520,250,Math.PI,0);ctx.fill();ctx.fillStyle='#75b492';ctx.fillRect(0,440,W,100)}
function drawCloud(x,y,s){ctx.fillStyle='#fff8e7aa';ctx.beginPath();ctx.arc(x,y,23*s,0,7);ctx.arc(x+30*s,y-12*s,32*s,0,7);ctx.arc(x+68*s,y,22*s,0,7);ctx.fill()}
function drawWorld(){const theme=level?.theme||'meadow';let sky=theme==='factory'?['#7e729d','#d58aa0']:theme==='castle'?['#3d315d','#a45f79']:['#79ccd9','#f9d88f'];const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,sky[0]);g.addColorStop(1,sky[1]);ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
  if(theme==='meadow'){drawCloud(100-camera*.12,90,1);drawCloud(530-camera*.16,150,.7);ctx.fillStyle='#9a80b7';for(let i=-1;i<6;i++){ctx.beginPath();ctx.arc(i*290-camera*.22+100,490,190,Math.PI,0);ctx.fill()}}
  if(theme==='factory'){ctx.fillStyle='#4e426c55';for(let i=-1;i<8;i++){let x=i*180-camera*.3;ctx.fillRect(x,170,105,300);ctx.beginPath();ctx.arc(x+52,170,52,Math.PI,0);ctx.fill()}ctx.strokeStyle='#f1c45b';ctx.lineWidth=8;for(let y=110;y<380;y+=120){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y-40);ctx.stroke()}}
  if(theme==='castle'){ctx.fillStyle='#30234555';for(let i=-1;i<7;i++){let x=i*210-camera*.25;ctx.fillRect(x,180,130,300);ctx.beginPath();ctx.moveTo(x,180);ctx.lineTo(x+65,90);ctx.lineTo(x+130,180);ctx.fill()}ctx.fillStyle='#efb95844';ctx.beginPath();ctx.arc(780,95,58,0,7);ctx.fill()}
  for(const p of platforms)drawPlatform(p,theme);for(const h of hazards)drawHazard(h);for(const c of cages)drawCage(c);drawExit();for(const e of enemies)drawEnemy(e);for(const p of projectiles)drawProjectile(p);if(hero.invuln<=0||Math.floor(performance.now()/80)%2)drawHero();for(const p of particles)drawParticle(p)}
function drawPlatform(p,theme){let x=p.x-camera;if(x>W+50||x+p.w<-50)return;ctx.fillStyle=p.bridge?'#fff1ce':theme==='factory'?'#b26f77':theme==='castle'?'#7b5c79':'#7cb88c';ctx.fillRect(x,p.y,p.w,p.h);ctx.fillStyle=p.bridge?'#eee0ba':theme==='factory'?'#f2bb62':theme==='castle'?'#d09a78':'#e7ae64';ctx.fillRect(x,p.y,p.w,10);ctx.strokeStyle='#513b51';ctx.lineWidth=3;ctx.strokeRect(x,p.y,p.w,p.h)}
function drawHazard(h){let x=h.x-camera;ctx.fillStyle='#c65c6f';for(let i=0;i<h.w;i+=22){ctx.beginPath();ctx.moveTo(x+i,h.y+h.h);ctx.lineTo(x+i+11,h.y);ctx.lineTo(x+i+22,h.y+h.h);ctx.fill()}ctx.fillStyle='#ffe3a1';ctx.fillRect(x,h.y+h.h-10,h.w,10)}
function drawExit(){let x=level.exit-camera,open=cages.every(c=>c.saved)&&!enemies.some(e=>!e.dead&&(e.kind==='sprinkles'||e.kind==='king'));ctx.fillStyle=open?'#f5c454':'#6e587c';ctx.fillRect(x,350,72,110);ctx.strokeStyle='#4a334e';ctx.lineWidth=4;ctx.strokeRect(x,350,72,110);ctx.fillStyle='#fff1ce';ctx.beginPath();ctx.arc(x+52,405,5,0,7);ctx.fill();ctx.fillStyle='#fff8e8';ctx.font='700 12px Fredoka';ctx.textAlign='center';ctx.fillText(open?'EXIT →':'LOCKED',x+36,334)}
function drawSwitch(s){if(s.hit)return;let x=s.x-camera;ctx.fillStyle='#845b8f';ctx.fillRect(x-9,s.y,18,50);circle(x,s.y,16,'#efbd51');ctx.fillStyle='#4b334e';ctx.font='700 17px Fredoka';ctx.textAlign='center';ctx.fillText('!',x,s.y+6)}
function drawCage(c){let x=c.x-camera;if(c.saved){drawPretzel(x+29,c.y+42,true);return}ctx.fillStyle='#4b334e';ctx.fillRect(x,c.y,c.w,7);ctx.fillRect(x,c.y+65,c.w,7);for(let i=5;i<c.w;i+=13)ctx.fillRect(x+i,c.y,5,72);drawPretzel(x+29,c.y+42,false);ctx.fillStyle='#f3bf53';ctx.font='700 10px Fredoka';ctx.textAlign='center';ctx.fillText('●'.repeat(c.hp),x+29,c.y-8)}
function drawPretzel(x,y,happy){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#713e3d';ctx.lineWidth=10;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-12,12);ctx.bezierCurveTo(-27,-6,-12,-23,0,-7);ctx.bezierCurveTo(12,-23,27,-6,12,12);ctx.bezierCurveTo(5,21,-5,21,-12,12);ctx.stroke();ctx.fillStyle='#fff6dd';circle(-6,1,2.2,'#fff6dd',null);circle(6,1,2.2,'#fff6dd',null);ctx.strokeStyle='#fff6dd';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,7,5,happy?0:Math.PI, happy?Math.PI:Math.PI*2);ctx.stroke();ctx.restore()}
function drawHero(){let x=hero.x-camera,y=hero.y,bob=hero.onGround?Math.sin(performance.now()/90)*1.5:0;ctx.save();ctx.translate(x+hero.w/2,y+31+bob);ctx.scale(hero.dir,1);ctx.fillStyle='#d95875';ctx.beginPath();ctx.moveTo(-18,-15);ctx.lineTo(-42,27);ctx.lineTo(-16,19);ctx.fill();circle(0,0,29,'#e79a4a','#513846',4);circle(0,0,10,'#ffd27a','#513846',3);ctx.fillStyle='#f7c363';ctx.beginPath();ctx.arc(-9,-10,7,0,7);ctx.arc(10,-11,6,0,7);ctx.fill();ctx.fillStyle='#ecf0e8';ctx.fillRect(-24,-31,34,10);ctx.strokeRect(-24,-31,34,10);ctx.fillStyle='#d65070';ctx.beginPath();ctx.moveTo(-18,-31);ctx.lineTo(-10,-54);ctx.lineTo(-3,-31);ctx.fill();ctx.stroke();circle(-9,-1,2.5,'#32243e',null);circle(10,-1,2.5,'#32243e',null);ctx.strokeStyle='#32243e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(1,8,7,.15,2.9);ctx.stroke();ctx.fillStyle='#7c5c8f';ctx.fillRect(19,8,20,6);circle(39,11,7,'#fff0cf','#513846',2);ctx.restore()}
function drawEnemy(e){let x=e.x-camera,y=e.y;if(x>W+120||x<-130)return;ctx.save();ctx.translate(x+e.w/2,y+e.h/2);if(e.kind==='roller')ctx.rotate(performance.now()/250*e.dir);else ctx.rotate(Math.sin(performance.now()/260+e.x)*.04);let boss=e.kind==='king',spr=e.kind==='sprinkles',r=e.w/2;circle(0,0,r,e.flash?'#fff':boss?'#9c56aa':spr?'#e7658c':e.kind==='archer'?'#f0a050':'#db7895','#4c334d',4);circle(0,0,boss?18:spr?13:10,'#efc67b','#4c334d',3);circle(-10,-3,3,'#34233e',null);circle(10,-3,3,'#34233e',null);ctx.strokeStyle='#34233e';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,10,8,.2,2.9);ctx.stroke();ctx.fillStyle=boss?'#f2c249':'#796092';ctx.fillRect(-18,-r-6,36,11);ctx.strokeRect(-18,-r-6,36,11);if(boss){ctx.beginPath();ctx.moveTo(-18,-r-6);ctx.lineTo(-11,-r-22);ctx.lineTo(0,-r-7);ctx.lineTo(11,-r-22);ctx.lineTo(18,-r-6);ctx.fill();ctx.stroke()}ctx.restore()}
function drawProjectile(p){let x=p.x-camera;if(p.kind==='cream')circle(x,p.y,9,'#fff7db','#d8c79f',2);else if(p.kind==='reflected')circle(x,p.y,13,'#fff3a0','#fff',4);else circle(x,p.y,p.kind==='orb'?12:7,p.kind==='orb'?'#f69abb':'#f5cf5d','#563750',2)}
function drawParticle(p){ctx.fillStyle=p.color;ctx.fillRect(p.screen?p.x:p.x-camera,p.y,p.r,p.r*(p.screen?1.8:1))}
function draw(){if(scene==='title'||scene==='story'||scene==='levelIntro')drawBackdrop();else drawWorld()}
function frame(t){const dt=Math.min(.034,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(frame)}

function pressKey(k,down){if(down&&!input[k])input[k+'Press']=true;input[k]=down}
document.querySelector('#startButton').addEventListener('click',()=>{tone(520,.08);storyStart()});document.querySelector('#continueButton').addEventListener('click',()=>showLevelIntro(0));document.querySelector('#skipStory').addEventListener('click',()=>showLevelIntro(0));document.querySelector('#nextStory').addEventListener('click',nextStory);document.querySelector('#levelButton').addEventListener('click',()=>loadLevel(levelIndex));document.querySelector('#dialogueNext').addEventListener('click',advanceDialogue);document.querySelector('#playAgain').addEventListener('click',()=>location.reload());document.querySelector('#muteButton').addEventListener('click',e=>{muted=!muted;e.currentTarget.textContent=muted?'×':'♪';say(muted?'Sound muted':'Sound on')});
const keyMap={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'jump',ArrowUp:'jump',w:'jump',W:'jump',j:'shoot',J:'shoot'};addEventListener('keydown',e=>{const k=keyMap[e.key];if(k){e.preventDefault();pressKey(k,true)}if((scene==='dialogue')&&(e.key==='Enter'||e.key===' '))advanceDialogue()});addEventListener('keyup',e=>{const k=keyMap[e.key];if(k){e.preventDefault();pressKey(k,false)}});addEventListener('blur',()=>Object.keys(input).forEach(k=>input[k]=false));

updateHud();drawBackdrop();requestAnimationFrame(frame);
